export const CAMPAIGN_SUGGESTIONS_PLACEMENT_ID =
  '444966bb-f5cd-48a1-839e-21d9cda0c0fa';

export enum QUERY_PARAMS {
  CAMPAIGN_SUGGESTION_ID = 'campaignSuggestionId',
  CAMPAIGN_ID = 'campaignId',
}

export enum MODULE_STATUS {
  LOADING,
  ERROR_MISSING_CAMPAIGN_SUGGESTION,
  ERROR_CAMPAIGN_SUGGESTION_NOT_VALID,
  SUCCESS,
}
