export const MODULE_ID = 'BM_EDITOR'
export const ADD_APPLICATION_TYPE = 'addApplication'
export const MIGRATE_TYPE = 'migrate'
export const LIVE_PREVIEW_REFRESH_TYPE = 'refreshLivePreview'
export const BIZ_MGR_NAMESPACE = 'BusinessManager'
